### ISSUE TITLE
`jq-interactively` should support C-p and C-n

### ISSUE THREAD

**Issue by matthew-piziak** [ljos/jq-mode#16]
Invoking `C-p` (previous input) should bring up the last query. This is conventional for Emacs commands with history.

**Comment by ljos** [comment]
Sorry for the delay. I just investigated this and C-p is previous-line, not previous input. M-p is previous-history-element, and this works as expected.

Thank you for reporting.

**Comment by matthew-piziak** [comment]
Whoops! That was a brain fart on my part. Thanks for being so gracious about it!
