### ISSUE TITLE
Ability to have raw output with jq-interactively

### ISSUE THREAD

**Issue by gvol** [ljos/jq-mode#32]
I wanted to convert a bunch of log lines to a csv.  `jq-interactively` worked amazingly well, but I ultimately wanted to be able to use the `-r` option to jq so that I would just print out the result instead of a json string with the result in it.

I was thinking you could use C-r or M-r or toggle raw output.

If you're not opposed to the idea, I might even try to throw together a PR.

**Comment by ljos** [comment]
I am not opposed. Please do write a PR if you find the time.
