### ISSUE TITLE
Bad indentation of objects

### ISSUE THREAD

**Issue by VPanteleev-S7** [ljos/jq-mode#40]
Hi, thanks for this package!

I noticed that indentation rules sometimes don't behave well. One case I noticed today is object literals:

```jq
{
"foo":1,
"bar":2,
"baz":3
}
```

Currently, this gets formatted as:
```jq
{
  "foo":1,
	 "bar":2,
		"baz":3
}
```
which isn't very useful.

**Comment by ljos** [comment]
Hi, thank you for the bug report. I think it should be fixed now.
