### ISSUE TITLE
Indented JSON

### ISSUE THREAD

**Issue by mcraveiro** [ljos/jq-mode#8]
Hi,

Thanks very much for a great mode, I was using jq from the command line and this is much better! One small question though: when I use ```jq-interactively``` on a indented buffer, the output buffer appears to be un-indented. Is there some option I can set for the output to become indented?

Thanks for your time.

Marco

**Comment by ljos** [comment]
If you set `jq-interactive-default-options` to `""` it should indent. I will make a commit to make that the default.

**Comment by ljos** [comment]
it will however not keep the indentation that you had before. It just uses the indentation from jq directly.

**Comment by mcraveiro** [comment]
works like a charm, thanks very much! One more question - my buffer was originally in JSON mode, but when I apply ```jq-interactively``` I can't see the font-lock (although emacs does say JSON mode). Is this expected? It's not a problem really, more of a question in case there is something i can toggle to get font-lock to come out.

Cheers

**Comment by ljos** [comment]
This is the problem I describe in #7. I haven't figured out how to get the font-lock to apply to text in an overlay. I am thinking about a different way of doing it, but for now you will have to live without colours.

**Comment by mcraveiro** [comment]
Aha, now I understand your comments! great, thanks, not a major issue - mode is *extremely* useful as it is, thanks very much!
